#!/usr/bin/env bash
setopt -e
# First of all, sign in!
op list vaults > /dev/null 2>&1 || eval $(op signin costian)

if [[ ! -f ~/.ssh/id_ed25519 ]]; then
	op signin costian jamescostian@gmail.com
	op
	mkdir .ssh
	op get document 5fqgog25ivec34grsyqbofjd6m > ~/.ssh/id_ed25519
	op get document lhif5tpa3dm3imo52vdjbrxuci > ~/.ssh/id_ed25519.pub
fi

if [[ ! -f ~/.config/sublime-text-3/Local/License.sublime_license ]]; then
	op get item Sublime\ Text | jq '.details.sections[0].fields[1].v' -r > ~/.config/sublime-text-3/Local/License.sublime_license
fi

if [[ ! -f ~/.gnupg/pubring.kbx ]]; then
	op get document xhrjl3vs5i22tdiu2lmv7mgq4m | gpg --import -
	expect -c "spawn gpg --edit-key 77E30DB4F230282981ED38EEDDF677A250F99DFD trust quit; send \"5\ry\r\"; expect eof"
fi


function add_wifi_passwords {
	for WIFI_UUID in $(op list items | jq '.[] | select(.templateUuid == "109").uuid' -r); do
		WIFI_JSON="$(op get item $WIFI_UUID)"
		WIFI_NAME="$(echo $WIFI_JSON | jq '.overview.title' -r)"
		# Create this wifi connection if it doesn't exist
		if ! nmcli c show "$WIFI_NAME" 2&>1 > dev/null; then
			WIFI_LOGIN_JSON="$(echo $WIFI_JSON | jq '.details.sections | .[] | select(has("fields")).fields | .[]')"
		fi
		nmcli c add type wifi con-name "$WIFI_NAME" ifname wlan0 ssid "$(echo $WIFI_LOGIN_JSON | jq 'select(.t == "base station name").v' -r)"
		nmcli c modify "$WIFI_NAME" wifi-sec.key-mgmt wpa-psk wifi-sec.psk "$(echo $WIFI_LOGIN_JSON | jq 'select(.t == "base station password").v' -r)"
	done
}

