#!/usr/bin/env bash
set -eo pipefail
if [[ ! -s ~/.config/Code/User/extensions ]]; then
	echo "YOU CANNOT INSTALL/UNINSTALL VS CODE EXTENSIONS WHEN YOU HAVE NO VS CODE EXTENSIONS!"
	exit 1
fi
# Don't bother if the list of extensions is identical to what's already installed
if cmp <(code --list-extensions) ~/.config/Code/User/extensions; then
	exit 0
fi
echo "Installing/uninstalling some VS Code extensions..."

icdiff <(code --list-extensions) ~/.config/Code/User/extensions
# First, install the packages that are in the file but not locally installed
diff --old-line-format="" --unchanged-line-format="" <(code --list-extensions) ~/.config/Code/User/extensions | xargs -rL 1 code --install-extension
# Next, uninstall the packages that aren't in the file but are locally installed
diff --new-line-format="" --unchanged-line-format="" <(code --list-extensions) ~/.config/Code/User/extensions | xargs -rL 1 code --uninstall-extension
