#!/usr/bin/env bash
set -eo pipefail

if ! hash js-beautify 2> /dev/null; then
	set +e
	npm install --global js-beautify || sudo npm install --global js-beautify
	set -e
fi

if [[ "$(uname)" != "Darwin" ]] && ! hash mullvad 2> /dev/null; then
	# This may not be the latest version, but running `update` in a terminal will fix that
	wget --content-disposition https://mullvad.net/en/download/deb/2020.5/ -O mullvad.deb
	sudo dpkg -i mullvad.deb && rm mullvad.deb
fi

if [[ "$(uname)" != "Darwin" ]] && ! hash minecraft-launcher 2> /dev/null; then
	wget https://launcher.mojang.com/download/Minecraft.deb
	set +e
	sudo dpkg -i Minecraft.deb
	sudo apt-get install -fyq
	rm Minecraft.deb
	set -e
fi

if [[ "$(uname)" != "Darwin" && ! -d "/usr/local/bin/op" ]] && ! hash op 2> /dev/null; then
	curl https://cache.agilebits.com/dist/1P/op/pkg/v1.0.0/op_linux_amd64_v1.0.0.zip -o op.zip
	unzip op.zip
	rm op.zip op.sig
	sudo mv op /usr/local/bin
fi

if [[ "$(uname)" != "Darwin" ]] && ! hash 1password 2> /dev/null; then
  sudo apt-key --keyring /usr/share/keyrings/1password.gpg adv --keyserver keyserver.ubuntu.com --recv-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
	echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password.gpg] https://onepassword.s3.amazonaws.com/linux/debian edge main' | sudo tee /etc/apt/sources.list.d/1password.list
	sudo apt update && sudo apt install 1password
fi

if { [[ "$(uname)" != "Darwin" ]] && ! fc-list | grep Powerline > /dev/null; } || { [[ "$(uname)" = "Darwin" ]] && ! system_profiler SPFontsDataType | grep Powerline > /dev/null; }; then
	git clone https://github.com/powerline/fonts.git --depth=1
	cd fonts
	./install.sh
	cd ..
	rm -rf fonts
fi

# Firefox Developer Edition... what a PITA
# It updates frequently enough (not automatically) that it's worth just reinstalling every time, unless it's currently running
if [[ "$(uname)" != "Darwin" ]] && ! pgrep 'firefox-devedition' > /dev/null; then
	curl -L 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US' | sudo tar -xjC /opt
	sudo rm -Rf /opt/firefox-devedition
	sudo mv /opt/firefox /opt/firefox-devedition
	sudo mv /opt/firefox-devedition/firefox-bin /opt/firefox-devedition/firefox-devedition-bin
	sudo mv /opt/firefox-devedition/firefox /opt/firefox-devedition/firefox-devedition
fi
if [[ "$(uname)" != "Darwin" && ! -f ~/.local/share/applications/firefox-devedition.desktop ]]; then
	mkdir -p ~/.local/share/applications
	echo "[Desktop Entry]" > ~/.local/share/applications/firefox-devedition.desktop
	echo "Name=Firefox Developer Edition" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Exec=/opt/firefox-devedition/firefox-devedition %u" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Terminal=false" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Icon=/opt/firefox-devedition/browser/chrome/icons/default/default128.png" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Type=Application" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Categories=Application;Network;X-Developer;" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "StartupWMClass=Firefox Developer Edition" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;" >> ~/.local/share/applications/firefox-devedition.desktop
	chmod +x ~/.local/share/applications/firefox-devedition.desktop
fi
