#!/usr/bin/env bash
set -eo pipefail

if [[ ! -d "$HOME/.cargo" ]] && ! hash rustc 2> /dev/null; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile complete --default-toolchain beta -y
fi

if [[ ! -d "/opt/go" ]] && ! hash go 2> /dev/null; then
	curl -L https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz | sudo tar -xzC /opt
fi

if [[ ! -f "/usr/local/bin/minikube" ]] && ! hash minikube 2> /dev/null; then
	sudo curl -Lo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
	sudo chmod a+x /usr/local/bin/minikube
fi

if [[ ! -f ~/.nanorc ]]; then
	curl https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh | sh
fi

if ! hash mullvad 2> /dev/null; then
	# This may not be the latest version, but running `update` in a terminal will fix that
	wget --content-disposition https://mullvad.net/en/download/deb/2020.4/ -O mullvad.deb
	sudo dpkg -i mullvad.deb && rm mullvad.deb
fi

if ! hash minecraft-launcher 2> /dev/null; then
	wget https://launcher.mojang.com/download/Minecraft.deb
	set +e
	sudo dpkg -i Minecraft.deb
	sudo apt-get install -fyq
	rm Minecraft.deb
	set -e
fi

if [[ ! -d "/usr/local/bin/op" ]] && ! hash op 2> /dev/null; then
	curl https://cache.agilebits.com/dist/1P/op/pkg/v1.0.0/op_linux_amd64_v1.0.0.zip -o op.zip
	unzip op.zip
	rm op.zip op.sig
	sudo mv op /usr/local/bin
fi

if ! fc-list | grep Powerline > /dev/null; then
	git clone https://github.com/powerline/fonts.git --depth=1
	cd fonts
	./install.sh
	cd ..
	rm -rf fonts
fi

# Firefox Developer Edition... what a PITA
# It updates frequently enough (not automatically) that it's worth just reinstalling every time, unless it's currently running
if ! pgrep 'firefox-devedition' > /dev/null; then
	curl -L 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US' | sudo tar -xjC /opt
	sudo rm -Rf /opt/firefox-devedition
	sudo mv /opt/firefox /opt/firefox-devedition
	sudo mv /opt/firefox-devedition/firefox-bin /opt/firefox-devedition/firefox-devedition-bin
	sudo mv /opt/firefox-devedition/firefox /opt/firefox-devedition/firefox-devedition
fi
if [[ ! -f ~/.local/share/applications/firefox-devedition.desktop ]]; then
	mkdir -p ~/.local/share/applications
	echo "[Desktop Entry]" > ~/.local/share/applications/firefox-devedition.desktop
	echo "Name=Firefox Developer Edition" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Exec=/opt/firefox-devedition/firefox-devedition %u" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Terminal=false" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Icon=/opt/firefox-devedition/browser/chrome/icons/default/default128.png" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Type=Application" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "Categories=Application;Network;X-Developer;" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "StartupWMClass=Firefox Developer Edition" >> ~/.local/share/applications/firefox-devedition.desktop
	echo "MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;" >> ~/.local/share/applications/firefox-devedition.desktop
	chmod +x ~/.local/share/applications/firefox-devedition.desktop
fi
