#!/usr/bin/env bash
# I wish ~/.config was all I needed to check in to git, but it's not. Some things have be installed elsewhere
# You can pass this a prefix, e.g. /mnt, if using this in an installer. This takes care of all the files that are needed outside of ~/.config
touch "$1/home/james/.hushlogin"
# Why Konsole puts its rc file in ~/.config but the rest of its config in ~/.local/share is beyond me
mkdir -p "$1/home/james/.local/share"
cd "$1/home/james/.local/share"
rm -Rf konsole
ln -s ../../.config/konsole

if [[ "$1" == "/mnt" ]]; then
	# This is being run from the NixOS installer.
	# My setup script that gets run by install-nixos runs _before_ rebooting - I'd like the setup script to also run after rebooting, so that it can do stuff like copy wifi secrets
	mv /mnt/home/james/.config/zsh-james/.zshrc /mnt/home/james/.config/zsh-james/real.zshrc
	echo "/home/james/.config/setup.sh" > /mnt/home/james/.config/zsh-james/.zshrc
	echo "source /home/james/.config/zsh-james/real.zshrc" >> /mnt/home/james/.config/zsh-james/.zshrc
	echo "mv /home/james/.config/zsh-james/real.zshrc /home/james/.config/zsh-james/.zshrc" >> /mnt/home/james/.config/zsh-james/.zshrc
else
	~/.config/scripts-james/helpers/make_ssh_use_my_config
fi
