#!/usr/bin/env bash
# I wish ~/.config was all I needed to check in to git, but it's not. Some things have be installed elsewhere
# You can pass this a prefix, e.g. /mnt, if using this in an installer. This takes care of all the files that are needed outside of ~/.config
touch "$1/home/james/.hushlogin"
# Why Konsole puts its rc file in ~/.config but the rest of its config in ~/.local/share is beyond me
mkdir -p "$1/home/james/.local/share"
cd "$1/home/james/.local/share"
rm -Rf konsole
ln -s ../../.config/konsole
# I'm using rupa/z which expects there to be a ~/.z file, so I'll just touch it:
touch "$1/home/james/.z"

if [[ "$1" == "/mnt" ]]; then
	# This is being run from the NixOS installer.
	# My setup script that gets run by install-nixos runs _before_ rebooting - I'd like the setup script to also run after rebooting, so that it can do stuff like copy wifi secrets
	mv /mnt/home/james/.config/zsh-james/.zshrc /mnt/home/james/.config/zsh-james/real.zshrc
	echo "/home/james/.config/setup.sh" > /mnt/home/james/.config/zsh-james/.zshrc
	# After running setup, source my real zshrc
	echo "source /home/james/.config/zsh-james/real.zshrc" >> /mnt/home/james/.config/zsh-james/.zshrc
	# KDE has a nasty habbit of tryna overwrite my user-dirs.dirs the first time around - combat that
	echo "cd .config; git checkout -- user-dirs.dirs; cd .." >> /mnt/home/james/.config/zsh-james/.zshrc
	# Finally, prevent this stuff from being run again:
	echo "mv /home/james/.config/zsh-james/real.zshrc /home/james/.config/zsh-james/.zshrc" >> /mnt/home/james/.config/zsh-james/.zshrc
else
	~/.config/scripts-james/helpers/make_ssh_use_my_config
fi
