#!/usr/bin/env bash
# When using my install-nixos script, the installer will clone a repo to /etc/nixos in hopes of being usable by others; however, this is not exactly what I want.
# Really, I want all of those files to end up in ~/.config - this file achieves that, and this file is run by setup.sh when using my install-nixos script
mkdir -p /mnt/home/james/.config

# Move all files from /mnt/etc/nixos (from the initial git clone) to $HOME/.config, where they belong.
# But in order to do that, first recreate the directory structure
cd /mnt/etc/nixos
find . -type d -exec mkdir -p /mnt/home/james/.config/{} \;
# Now do the actual moving (excluding .nix files)
find . -type f -not -name "*.nix" -exec mv {} /mnt/home/james/.config/{} \;
# There is one exception tho - ~/.config/nixpkgs
mv /mnt/etc/nixos/nixpkgs /home/james/.config

# The .nix files shouldn't be *moved*, but they still should be *copied*
find . -type f -not -name "*.nix" -exec cp {} /mnt/home/james/.config/{} \;
find . -type f -not -name "*.nix" -exec chown $MY_USER_ID:100 /mnt/home/james/.config/{} \;

# Don't leave behind a bunch of empty directories though!
find . ! -path . -type d -exec rm -Rf /mnt/etc/nixos/{} \;
