#!/usr/bin/env bash

# Every file in /etc/apt/sources.list.d must be listed in this file. If a file is there that isn't in here, then it won't end up getting installed on other machines.
for source in /etc/apt/sources.list.d/*.list; do
	if ! grep "$source" $0 > /dev/null; then
		echo "You have an apt source that is not in your dotfiles."
		echo "Please add or instructions to get it to $0"
		echo "The source in question is $source"
		exit 29
	fi
done

# VS Code
if [[ ! -f /etc/apt/sources.list.d/vscode.list ]]; then
	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
	sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
	cat packages.microsoft.gpg | sudo apt-key add -
	rm -f packages.microsoft.gpg
	sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
fi

# Yarn
if [[ ! -f /etc/apt/sources.list.d/yarn.list ]]; then
	curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
	echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list > /dev/null
fi

# Google Chrome
if [[ ! -f /etc/apt/sources.list.d/google-chrome-beta.list ]]; then
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome-beta.list'
	# Somehow, this will also end up generating this apt source: /etc/apt/sources.list.d/google-chrome.list
fi

# Specifiv version of Node.js
if [[ ! -f /etc/apt/sources.list.d/nodesource.list ]]; then
	curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - > /dev/null
fi

# MS Teams
if [[ ! -f /etc/apt/sources.list.d/teams.list ]]; then
	echo 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main' | sudo tee /etc/apt/sources.list.d/teams.list > /dev/null
fi

if [[ ! -f /etc/apt/sources.list.d/signal-xenial.list ]]; then
	curl -s https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -
	echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list > /dev/null
fi

# Add Multiverse
if ! grep multiverse /etc/apt/sources.list | grep '^\s*deb' > /dev/null; then
	sudo add-apt-repository multiverse
fi

# /etc/apt/sources.list.d/steam.list may be created by steam
# /etc/apt/sources.list.d/system76-ubuntu-pop-focal.list may be created on system76 machines
# /etc/apt/sources.list.d/openrazer-ubuntu-stable-groovy.list may be created when installing open razer

sudo apt-get update
