#!/usr/bin/env bash
if [[ -z "$MULTITENANT_SUFFIX" ]]; then
	echo "No multitenant suffix specified; this script is not made to be run by itself, instead setup.sh should call it"
	exit 1
fi

./install-if-not-exists bash awk file sudo ssh curl zsh rsync rg unzip
./make-ssh-use-my-config

cat <<EOF > "$HOME/.config/uninstall$MULTITENANT_SUFFIX"
rm -Rf ~/.config/*$MULTITENANT_SUFFIX
cat ~/.ssh/config | sed -e "/Match exec.*"'_$'"MULTITENANT_SUFFIX == _$MULTITENANT_SUFFIX.*/,+3d" > ~/.ssh/config-uninstalled
mv ~/.ssh/config-uninstalled ~/.ssh/config
EOF
