#!/usr/bin/env bash
# OMZ has a git plugin that provides git_current_branch and a couple of the ZSH aliases rely on git_current_branch, so this file makes them work
git rev-parse --abbrev-ref HEAD 2> /dev/null || git symbolic-ref --short HEAD 2> /dev/null
