#!/usr/bin/env bash
# SSHInject your configuration!
# Copies my SSH public key to the server specified, and then installs my .config
set -eo pipefail
ssh-copy-id $@
ssh -t $@ 'sh -c "`curl -L https://jami.am || wget -qO - https://jami.am`"'
